DROP DATABASE IF EXISTS web_buh;
CREATE DATABASE web_buh;
USE web_buh;


CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    nickname VARCHAR(255) UNIQUE,
    avatar_base64 LONGTEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_user INT NOT NULL,
    title TEXT NOT NULL,
    text TEXT NOT NULL,
    likes INT DEFAULT 0,
    dislikes INT DEFAULT 0,
    publication_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    photo_base64 LONGTEXT,
    FOREIGN KEY (id_user) REFERENCES users(id) ON DELETE CASCADE
);